### ISSUE TITLE
RSSDIVCS DataSet

### ISSUE THREAD

**Issue by nice7875** [TangXu-Group/Remote-Sensing-Images-Classification#2]
Hello, is it convenient to provide RSSDIVCS data set? Or his download address, which I've been looking for a long time.

Thank you very much.

**Comment by nice7875** [comment]
I'm sorry to bother you. I already found it

**Comment by cheer00** [comment]
would you please share the RSSDIVCS data set with me? Very thanks?

> I'm sorry to bother you. I already found it

**Comment by cheer00** [comment]
@nice7875 Would you please share the RSSDIVCS data set with me? Very thanks?

**Comment by young717-xs** [comment]
@nice7875 Would you please share the RSSDIVCS data set with me?Many thanks！

**Comment by qiuliwen** [comment]
您能与我分享 RSSDIVCS 数据集吗？非常感谢！

**Comment by qiuliwen** [comment]
> 很抱歉打扰您。我已经找到了

您能与我分享 RSSDIVCS 数据集吗？非常感谢！

**Comment by young717-xs** [comment]
对不起，我也还没获得RSSDIVCS数据集。







-----原始邮件-----
发件人:qiuliwen ***@***.***>
发送时间:2024-05-08 21:57:18 (星期三)
收件人: TangXu-Group/Remote-Sensing-Images-Classification ***@***.***>
抄送: young717-xs ***@***.***>, Comment ***@***.***>
主题: Re: [TangXu-Group/Remote-Sensing-Images-Classification] RSSDIVCS DataSet (Issue #2)






您能与我分享 RSSDIVCS 数据集吗？非常感谢！
